### PR TITLE
Migrate to 12.0 :camel:

### PR DESCRIPTION
**Pull request by ivy-rew**
A friendly conversion provided by market-up2date-keeper :robot: :handshake:

### CODE REVIEW

**Comment by nqhoan-axonivy** [comment]
[WAIT] Contacted Thomas already but still cannot get an accesskey for DeepL API testing
=> Discuss with Alex Scharping to create a new account => need a credit card

**Comment by ivy-rew** [comment]
> [WAIT] Contacted Thomas already but still cannot get an accesskey for DeepL API testing => Next action: Discuss with Alex Scharping to create a new account => need a credit card

IMHO we could also migrate the project to 12 without actually testing the compliance with the real life API of deepL. 
We have a mock service in test project which we can use to simulate the real execution ... with it we can verify the functionality of the connector and demo.

**Comment by ivy-rew** [comment]
I'll document this app.yaml development approach in readme @nqhoan-axonivy

**Comment by nqhoan-axonivy** [comment]
Hurray... got it. so let me go to next step

**Pull request merged**
